/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.bfh.lca._15h.client.ui;

import ch.bfh.lca._15h.client.model.RecordsTableModel;
import ch.bfh.lca._15h.library.DataSource;
import ch.bfh.lca._15h.library.Database.MSAccessDatabase;
import ch.bfh.lca._15h.library.impl.DBDataSource;
import ch.bfh.lca._15h.library.impl.DataSourceCSV;
import ch.bfh.lca._15h.library.impl.DataSourceJSON;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Cédric Michelet
 */
public class MainFrame extends javax.swing.JFrame {

    private RecordsTableModel recordsTableModel = null;
    private DataSource inputSource = null;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //init table model
        recordsTableModel = new RecordsTableModel(null);
        jTRecords.setModel(recordsTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTJSONPath = new javax.swing.JTextField();
        jBConvertToJSON = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFCSVFilePatient = new javax.swing.JTextField();
        jTFCSVFileActivity = new javax.swing.JTextField();
        jBCSVFileActivitySearch = new javax.swing.JButton();
        jBCSVFilePatientSearch = new javax.swing.JButton();
        jBCSVLoad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFDBFile = new javax.swing.JTextField();
        jBDBFilePatientSearch = new javax.swing.JButton();
        jBDBLoad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRecords = new javax.swing.JTable();
        jBCSVFileJSONSearch = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMLanguage = new javax.swing.JMenu();
        jRBEnglish = new javax.swing.JRadioButtonMenuItem();
        jRBGerman = new javax.swing.JRadioButtonMenuItem();
        jRBFrench = new javax.swing.JRadioButtonMenuItem();
        jMIQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Output to JSON file:");

        jTJSONPath.setText("c:\\sentinella\\test.json");
        jTJSONPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTJSONPathActionPerformed(evt);
            }
        });

        jBConvertToJSON.setText("Export");
        jBConvertToJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConvertToJSONActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sentinella Client (v1.0)");

        jLabel3.setText("Patient CSV file:");

        jLabel4.setText("Activities CSV file:");

        jTFCSVFilePatient.setText("C:\\sentinella\\Patient.csv");

        jTFCSVFileActivity.setText("C:\\sentinella\\Leistung.csv");

        jBCSVFileActivitySearch.setText("...");
        jBCSVFileActivitySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCSVFileActivitySearchActionPerformed(evt);
            }
        });

        jBCSVFilePatientSearch.setText("...");
        jBCSVFilePatientSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCSVFilePatientSearchActionPerformed(evt);
            }
        });

        jBCSVLoad.setText("Load");
        jBCSVLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCSVLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBCSVLoad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFCSVFilePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBCSVFilePatientSearch)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTFCSVFileActivity, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCSVFileActivitySearch)))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFCSVFilePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCSVFilePatientSearch)
                        .addComponent(jTFCSVFileActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBCSVFileActivitySearch)))
                .addGap(18, 18, 18)
                .addComponent(jBCSVLoad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CSV file", jPanel1);

        jLabel5.setText("MS Access Path:");

        jTFDBFile.setText("C:\\sentinella\\Leistungen.accdb");

        jBDBFilePatientSearch.setText("...");
        jBDBFilePatientSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDBFilePatientSearchActionPerformed(evt);
            }
        });

        jBDBLoad.setText("Load");
        jBDBLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDBLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(784, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFDBFile, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBDBFilePatientSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDBLoad)
                        .addGap(215, 215, 215))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDBFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBDBFilePatientSearch)
                        .addComponent(jBDBLoad)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MS Access DB", jPanel2);

        jTRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTRecords);

        jBCSVFileJSONSearch.setText("...");
        jBCSVFileJSONSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCSVFileJSONSearchActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMLanguage.setText("Language");

        jRBEnglish.setSelected(true);
        jRBEnglish.setText("English");
        jRBEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBEnglishActionPerformed(evt);
            }
        });
        jMLanguage.add(jRBEnglish);

        jRBGerman.setText("Deutsch");
        jMLanguage.add(jRBGerman);

        jRBFrench.setText("Français");
        jMLanguage.add(jRBFrench);

        jMenu1.add(jMLanguage);

        jMIQuit.setText("Quit");
        jMIQuit.setToolTipText("");
        jMIQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jMIQuit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTabbedPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTJSONPath, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCSVFileJSONSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBConvertToJSON)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTJSONPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConvertToJSON)
                    .addComponent(jBCSVFileJSONSearch))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("CSV file");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConvertToJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConvertToJSONActionPerformed
        //check that we have an input source
        if(inputSource == null) return;

        //check output path
        //@TODO check file path is valid
        File output = new File(jTJSONPath.getText());
        
        try {
            DataSourceJSON.writeBAGJSONToFile(inputSource, null, output.getAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConvertToJSONActionPerformed

    private void jTJSONPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTJSONPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTJSONPathActionPerformed

    private void jMIQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIQuitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMIQuitActionPerformed

    private void jRBEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBEnglishActionPerformed

    private void jBCSVFileActivitySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCSVFileActivitySearchActionPerformed
        //select a CSV file for activities
        JFileChooser fc = new JFileChooser();
        //@TODO filter file to CSV only
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTFCSVFileActivity.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jBCSVFileActivitySearchActionPerformed

    private void jBCSVFilePatientSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCSVFilePatientSearchActionPerformed
       //select a CSV file for patient
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        //@TODO filter file to CSV only
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTFCSVFilePatient.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jBCSVFilePatientSearchActionPerformed

    private void jBCSVLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCSVLoadActionPerformed
        File fPatient, fActivity;
        
        //check both files exists
        fPatient = new File(jTFCSVFilePatient.getText());
        fActivity = new File(jTFCSVFileActivity.getText());
        
        if(!fPatient.exists()) {
            //@TODO show error
            return;
        }
        
        if(!fActivity.exists()) {
            //@TODO show error
            return;
        }
        
        //create datasource in memory
        inputSource = new DataSourceCSV(fPatient.getAbsolutePath(), fActivity.getAbsolutePath());
        
        //reload table
        recordsTableModel.setDataSource(inputSource);
    }//GEN-LAST:event_jBCSVLoadActionPerformed

    private void jBCSVFileJSONSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCSVFileJSONSearchActionPerformed
        //select a json output
        JFileChooser fc = new JFileChooser();
        //@TODO filter file to json only
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTJSONPath.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jBCSVFileJSONSearchActionPerformed

    private void jBDBFilePatientSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDBFilePatientSearchActionPerformed
       //select a CSV file for patient
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        //@TODO filter file to accdb only
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTFDBFile.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jBDBFilePatientSearchActionPerformed

    private void jBDBLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDBLoadActionPerformed
        File fDB;
        
        //check file exists
        fDB = new File(jTFDBFile.getText());
        
        if(!fDB.exists()) {
            //@TODO show error
            return;
        }
        
        try {
            //create datasource in memory
            inputSource = new DBDataSource(new MSAccessDatabase(fDB.getAbsolutePath()));
        } catch (Exception ex) {
            //@TODO show/log error
            inputSource = null;
        }
        
        //reload table
        recordsTableModel.setDataSource(inputSource);
    }//GEN-LAST:event_jBDBLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCSVFileActivitySearch;
    private javax.swing.JButton jBCSVFileJSONSearch;
    private javax.swing.JButton jBCSVFilePatientSearch;
    private javax.swing.JButton jBCSVLoad;
    private javax.swing.JButton jBConvertToJSON;
    private javax.swing.JButton jBDBFilePatientSearch;
    private javax.swing.JButton jBDBLoad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMIQuit;
    private javax.swing.JMenu jMLanguage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRBEnglish;
    private javax.swing.JRadioButtonMenuItem jRBFrench;
    private javax.swing.JRadioButtonMenuItem jRBGerman;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCSVFileActivity;
    private javax.swing.JTextField jTFCSVFilePatient;
    private javax.swing.JTextField jTFDBFile;
    private javax.swing.JTextField jTJSONPath;
    private javax.swing.JTable jTRecords;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
